'use server';
import { compare,hash as passwordHash } from 'bcryptjs'; import { randomUUID } from 'crypto'; import { redirect } from 'next/navigation'; import { revalidatePath } from 'next/cache'; import { and,eq,isNull } from 'drizzle-orm'; import { z } from 'zod';
import { db } from '@/lib/db'; import { users,stacks,stackEntries,tokens } from '@/db/schema'; import { hash,makeToken,requireUser,signIn,signOut } from '@/lib/auth'; import { dateAdd,localDate,weekKey } from '@/lib/date';
const credentials=z.object({email:z.email().toLowerCase(),password:z.string().min(8)});
export async function register(_:unknown,fd:FormData){const parsed=credentials.safeParse(Object.fromEntries(fd));if(!parsed.success||fd.get('password')!==fd.get('confirm'))return{error:'Use a valid email and matching password (8+ characters).'};const existing=await db().select().from(users).where(eq(users.email,parsed.data.email)).limit(1);if(existing.length)return{error:'An account already exists for this email.'};const id=randomUUID();await db().insert(users).values({id,email:parsed.data.email,passwordHash:await passwordHash(parsed.data.password,12)});const token=await makeToken(id,'verify');console.info(`STACK verify: ${process.env.APP_URL??'http://localhost:3000'}/verify-email?token=${token}`);await signIn(id);redirect('/verify-email')}
export async function login(_:unknown,fd:FormData){const p=credentials.safeParse(Object.fromEntries(fd));if(!p.success)return{error:'Enter a valid email and password.'};const row=(await db().select().from(users).where(eq(users.email,p.data.email)).limit(1))[0];if(!row||!await compare(p.data.password,row.passwordHash))return{error:'Email or password is incorrect.'};await signIn(row.id);redirect(row.onboardingComplete?'/':'/onboarding')}
export async function logout(){await signOut();redirect('/')}
export async function forgot(_:unknown,fd:FormData){const email=z.email().safeParse(fd.get('email'));if(email.success){const row=(await db().select().from(users).where(eq(users.email,email.data.toLowerCase())).limit(1))[0];if(row){const token=await makeToken(row.id,'reset');console.info(`STACK reset: ${process.env.APP_URL??'http://localhost:3000'}/reset-password?token=${token}`)}}return{ok:true}}
export async function reset(_:unknown,fd:FormData){const p=z.string().min(8).safeParse(fd.get('password')),raw=fd.get('token');if(!p.success||typeof raw!=='string')return{error:'Password must contain at least 8 characters.'};const row=(await db().select().from(tokens).where(and(eq(tokens.tokenHash,hash(raw)),eq(tokens.kind,'reset'))).limit(1))[0];if(!row||row.expiresAt<new Date())return{error:'This reset link is invalid or expired.'};await db().update(users).set({passwordHash:await passwordHash(p.data,12),updatedAt:new Date()}).where(eq(users.id,row.userId));await db().delete(tokens).where(eq(tokens.id,row.id));redirect('/login')}
export async function verify(raw:string){const row=(await db().select().from(tokens).where(and(eq(tokens.tokenHash,hash(raw)),eq(tokens.kind,'verify'))).limit(1))[0];if(!row||row.expiresAt<new Date())return false;await db().update(users).set({emailVerifiedAt:new Date()}).where(eq(users.id,row.userId));await db().delete(tokens).where(eq(tokens.id,row.id));return true}
export async function timezone(fd:FormData){const u=await requireUser(),tz=z.string().refine(x=>{try{Intl.DateTimeFormat(undefined,{timeZone:x});return true}catch{return false}}).parse(fd.get('timezone'));await db().update(users).set({timezone:tz,onboardingComplete:new Date(),updatedAt:new Date()}).where(eq(users.id,u.id));redirect('/')}
export async function createStack(_:unknown,fd:FormData){const u=await requireUser(),p=z.object({name:z.string().trim().min(1).max(40),description:z.string().trim().max(160),frequency:z.enum(['DAILY','WEEKLY'])}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:'Add a name and choose a frequency.'};await db().insert(stacks).values({id:randomUUID(),userId:u.id,...p.data,description:p.data.description||null});redirect('/')}
export async function completeStack(id:string){const u=await requireUser(),s=(await db().select().from(stacks).where(and(eq(stacks.id,id),eq(stacks.userId,u.id),isNull(stacks.archivedAt))).limit(1))[0];if(!s)throw new Error('Stack not found');const today=localDate(new Date(),u.timezone);if(s.frequency==='WEEKLY'){const start=weekKey(today),existing=await db().select().from(stackEntries).where(eq(stackEntries.stackId,id));if(existing.some(e=>e.entryDate>=start&&e.entryDate<=dateAdd(start,6)))return}await db().insert(stackEntries).values({id:randomUUID(),stackId:id,entryDate:today}).onConflictDoNothing();revalidatePath('/');revalidatePath(`/stack/${id}`)}
export async function archiveStack(id:string){const u=await requireUser();await db().update(stacks).set({archivedAt:new Date()}).where(and(eq(stacks.id,id),eq(stacks.userId,u.id)));redirect('/')}
export async function deleteAccount(fd:FormData){const u=await requireUser();if(fd.get('confirm')!=='DELETE')return;await db().delete(users).where(eq(users.id,u.id));await signOut();redirect('/')}
